"""markdown source

Revision ID: 95cf2639c042
Revises: e23a09521e5a
Create Date: 2016-03-06 20:55:39.714263

"""

# revision identifiers, used by Alembic.
revision = '95cf2639c042'
down_revision = 'e23a09521e5a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('html', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('markdown', sa.Text(), nullable=True))
    op.drop_column('posts', 'text')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'markdown')
    op.drop_column('posts', 'html')
    ### end Alembic commands ###
