"""user.roles

Revision ID: 28560703dfa4
Revises: 42f048696f80
Create Date: 2016-02-09 22:45:20.977475

"""

# revision identifiers, used by Alembic.
revision = '28560703dfa4'
down_revision = '42f048696f80'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.Integer(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    ### end Alembic commands ###
