"""posts

Revision ID: d0ff8a3810ea
Revises: 28560703dfa4
Create Date: 2016-02-13 14:36:41.037132

"""

# revision identifiers, used by Alembic.
revision = 'd0ff8a3810ea'
down_revision = '28560703dfa4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'deleted', name='post_status'), server_default='draft', nullable=True),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='restrict'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    ### end Alembic commands ###
