"""comments markdown

Revision ID: 7512f57a17e2
Revises: 95cf2639c042
Create Date: 2016-03-06 21:59:15.350001

"""

# revision identifiers, used by Alembic.
revision = '7512f57a17e2'
down_revision = '95cf2639c042'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('html', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('markdown', sa.Text(), nullable=True))
    op.drop_column('comments', 'text')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'markdown')
    op.drop_column('comments', 'html')
    ### end Alembic commands ###
